version: "3.4"
service:
  postgres:
    image: postgres:13.2-alpine
    restart: always
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - currency-tracker-backend:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
